app/urls.py
from django.urls import include, path

urlpatterns = [
   # your other URL patterns go here
   path('', include('basketball_video_upload.urls')),
]

basketball_video_upload/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from basketball_video_upload.views import misc, players, coaches_and_admins, games

app_name = 'basketball_video_upload'

urlpatterns = [
    path('', misc.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', misc.logout_view, name='logout'),
    path('register/', misc.register, name='register'),
    path('choose_role/', misc.choose_role, name='choose_role'),
    path('upload_profile/', misc.upload_profile, name='upload_profile'),
    path('show_profile/', players.ProfileView.as_view(), name='show_profile'),
    path('games/new/', games.GameCreateView.as_view(), name='create_game'),
    path('list_all_games/', games.AllGameListView.as_view(), name='list_all_games'),
    path('list_personal_games/', games.PersonalGameListView.as_view(), name='list_personal_games'),
    path('list_all_players/', coaches_and_admins.PlayerListView.as_view(), name='list_all_players'),
    path('list_all_player_game_highlight_videos/', coaches_and_admins.AllPlayerGameHighlightVideoListView.as_view(),
         name='list_all_player_game_highlight_videos'),
    path('list_personal_player_game_highlight_videos/', players.PersonalPlayerGameHighlightVideoListView.as_view(),
         name='list_personal_player_game_highlight_videos'),
    path('view_individual_player_game_highlight_video/<int:video_id>/',
         players.IndividualPlayerHighlightVideoView.as_view(),
         name='view_individual_player_game_highlight_video'),
    path('player_game_highlight_videos/new/<int:id>', players.PlayerGameHighlightVideoCreateView.as_view(),
         name='create_player_game_highlight_video'),
    path('list_all_player_game_statistics/', coaches_and_admins.AllPlayerGameStatisticListView.as_view(),
         name='list_all_player_game_statistics'),
    path('list_personal_player_game_statistics/', players.PersonalPlayerGameStatisticListView.as_view(),
         name='list_personal_player_game_statistics'),
    path('view_individual_player_game_statistic/<int:game_id>/',
         players.IndividualPlayerGameStatisticView.as_view(),
         name='view_individual_player_game_statistic'),
    path('player_game_statistics/new/<int:id>', players.PlayerGameStatisticCreateView.as_view(),
         name='create_player_game_statistic'),
    path('admin/', admin.site.urls),
]

basketball_video_upload/views/games.py
from django.db.models import Count
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView

from basketball_video_upload.decorators import player_required
from basketball_video_upload.forms import GameForm
from basketball_video_upload.models import Game
from basketball_video_upload.views.s3 import upload_video_to_s3


@method_decorator(player_required, name='get')
class GameCreateView(CreateView):
    model = Game
    form_class = GameForm
    template_name = 'games/new_game.html'
    success_url = '/list_personal_games/'

    def form_valid(self, form):
        form.instance.player = self.request.user.profile
        return super().form_valid(form)


@method_decorator(player_required, name='get')
class AllGameListView(View):
    def get(self, request):
        games = Game.objects.all()
        return render(request, 'games/list_all_games.html',
                      {'games': games})


@method_decorator(player_required, name='get')
class PersonalGameListView(View):
    def get(self, request):
        games = Game.objects.filter(player=request.user.profile).annotate(
            has_highlight=Count('playergamehighlightvideo__game'),
            has_statistic=Count('playergamestatistic__game')
        )
        return render(request, 'games/list_personal_games.html',
                      {'games': games})

templates/games/list_all_games.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">All Games</h1>
        <table class="table table-striped mt-4">
            <thead>
            <tr>
                <th scope="col">Game Date</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for game in games %}
                <tr>
                    <td>{{ game.date }}</td>
                    <td>
                        <a href="{% url 'basketball_video_upload:view_individual_player_game_highlight_video' game.id %}"
                           class="btn btn-success">View
                            Highlight Video</a>
                        <a href="{% url 'basketball_video_upload:view_individual_player_game_statistic' game.id %}"
                           class="btn btn-warning">View
                            Statistics</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/games/list_personal_games.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Personal Games</h1>
        <button onclick="window.location.href='{% url 'basketball_video_upload:create_game' %}';"
                class="btn btn-primary create-btn">
            Create Game
        </button>
        <table class="table table-striped mt-4">
            <thead>
            <tr>
                <th scope="col">Game Date</th>
                <th scope="col">League Type</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for game in games %}
                <tr>
                    <td>{{ game.date }}</td>
                    <td>{{ game.type }}</td>
                    <td>
                        {% if game.has_highlight == 0 %}
                            <a href="{% url 'basketball_video_upload:create_player_game_highlight_video' game.id %}"
                               class="btn btn-primary">Create
                                Highlight Video</a>
                        {% else %}
                            <a href="{% url 'basketball_video_upload:view_individual_player_game_highlight_video' game.id %}"
                               class="btn btn-success">View
                                Highlight Video</a>
                        {% endif %}
                        {% if game.has_statistic == 0 %}
                            <a href="{% url 'basketball_video_upload:create_player_game_statistic' game.id %}"
                               class="btn btn-info">Create
                                Statistics</a>
                        {% else %}
                            <a href="{% url 'basketball_video_upload:view_individual_player_game_statistic' game.id %}"
                               class="btn btn-warning">View
                                Statistics</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

templates/games/new_game.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="container">
        <h2 class="mt-4">Create New Game</h2>
        <form method="post" class="mt-4">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Create</button>
        </form>
    </div>
{% endblock %}