app/urls.py
from django.urls import include, path

urlpatterns = [
   # your other URL patterns go here
   path('', include('basketball_video_upload.urls')),
]

basketball_video_upload/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from basketball_video_upload.views import misc, players, coaches_and_admins, games

app_name = 'basketball_video_upload'

urlpatterns = [
    path('', misc.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', misc.logout_view, name='logout'),
    path('register/', misc.register, name='register'),
    path('choose_role/', misc.choose_role, name='choose_role'),
    path('upload_profile/', misc.upload_profile, name='upload_profile'),
    path('show_profile/', players.ProfileView.as_view(), name='show_profile'),
    path('games/new/', games.GameCreateView.as_view(), name='create_game'),
    path('list_all_games/', games.AllGameListView.as_view(), name='list_all_games'),
    path('list_personal_games/', games.PersonalGameListView.as_view(), name='list_personal_games'),
    path('list_all_players/', coaches_and_admins.PlayerListView.as_view(), name='list_all_players'),
    path('list_all_player_game_highlight_videos/', coaches_and_admins.AllPlayerGameHighlightVideoListView.as_view(),
         name='list_all_player_game_highlight_videos'),
    path('list_personal_player_game_highlight_videos/', players.PersonalPlayerGameHighlightVideoListView.as_view(),
         name='list_personal_player_game_highlight_videos'),
    path('view_individual_player_game_highlight_video/<int:video_id>/',
         players.IndividualPlayerHighlightVideoView.as_view(),
         name='view_individual_player_game_highlight_video'),
    path('player_game_highlight_videos/new/<int:id>', players.PlayerGameHighlightVideoCreateView.as_view(),
         name='create_player_game_highlight_video'),
    path('list_all_player_game_statistics/', coaches_and_admins.AllPlayerGameStatisticListView.as_view(),
         name='list_all_player_game_statistics'),
    path('list_personal_player_game_statistics/', players.PersonalPlayerGameStatisticListView.as_view(),
         name='list_personal_player_game_statistics'),
    path('view_individual_player_game_statistic/<int:game_id>/',
         players.IndividualPlayerGameStatisticView.as_view(),
         name='view_individual_player_game_statistic'),
    path('player_game_statistics/new/<int:id>', players.PlayerGameStatisticCreateView.as_view(),
         name='create_player_game_statistic'),
    path('admin/', admin.site.urls),
]

templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<style>

</style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Basketball Video Upload{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<header class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'basketball_video_upload:home' %}">Basketball Video Upload App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    {% if request.user.profile.is_administrator %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'basketball_video_upload:list_all_players' %}">Players</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'basketball_video_upload:list_all_games' %}">Games</a>
                        </li>
                    {% elif request.user.profile.is_coach %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'basketball_video_upload:list_all_players' %}">Players</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'basketball_video_upload:list_all_games' %}">Games</a>
                        </li>
                    {% elif request.user.profile.is_player %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'basketball_video_upload:show_profile' %}">Profile</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'basketball_video_upload:list_personal_games' %}">Games</a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basketball_video_upload:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'basketball_video_upload:register' %}">Register</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'basketball_video_upload:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>
<main>
    {% block content %}{% endblock %}
</main>
<footer>
    <!-- Add your footer content here -->
</footer>


<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
</body>
<footer>
    <a href="https://www.flaticon.com/free-icons/ui" title="ui icons">Ui icons created by rukanicon - Flaticon</a>
</footer>
</html>

templates/home.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
        <div class="header text-center">
            <h1>Welcome to the Basketball Video Upload Application</h1>
            <p>This application allows you to upload and manage highlight videos of basketball games.</p>
        </div>
        <div class="icons d-flex justify-content-center">
            {% if request.user.is_authenticated %}
                {% if request.user.profile.is_administrator %}
                    <a href="{% url 'basketball_video_upload:list_all_players' %}" data-toggle="tooltip"
                       data-placement="top"
                       title="Players">
                        <i class="fas fa-user" style="font-size: 100px"></i> </a>
                    <a href="{% url 'basketball_video_upload:list_all_games' %}" data-toggle="tooltip"
                       data-placement="top"
                       title="Games">
                        <i class="fas fa-basketball-ball" style="font-size: 100px"></i>

                    </a>

                {% elif request.user.profile.is_coach %}
                    <a href="{% url 'basketball_video_upload:list_all_players' %}" data-toggle="tooltip"
                       data-placement="top"
                       title="Players">
                        <i class="fas fa-user" style="font-size: 100px"></i>
                    </a>
                    <a href="{% url 'basketball_video_upload:list_all_games' %}" data-toggle="tooltip"
                       data-placement="top"
                       title="Games">
                        <i class="fas fa-basketball-ball" style="font-size: 100px"></i>

                    </a>

                {% elif request.user.profile.is_player %}
                    <a href="{% url 'basketball_video_upload:show_profile' %}" data-toggle="tooltip"
                       data-placement="top"
                       title="Profile">
                        <i class="fas fa-users" style="font-size: 100px;"></i>

                    </a>
                    <a href="{% url 'basketball_video_upload:list_personal_games' %}" data-toggle="tooltip"
                       data-placement="top"
                       title="Games">
                        <i class="fas fa-basketball-ball" style="font-size: 100px"></i>
                    </a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}